/**
 * Copy-paste integration recipes shown in the console Documentation hub. Two families:
 *  - "Built-in (hosted)": the tenant's app is a plain OIDC client — the platform provides password, MFA,
 *    social, passkey and SAML on the hosted login with no per-mechanism code.
 *  - "Embedded / Backend": the tenant's app runs the ceremony itself, or a backend calls the APIs.
 *
 * Samples are backtick-free so they embed cleanly. ISSUER = your Aegis issuer host, GATEWAY = the API gateway.
 */

export type Lang = 'TypeScript' | 'Python' | 'Java' | 'Go';
export const LANGS: Lang[] = ['TypeScript', 'Python', 'Java', 'Go'];

export interface Recipe {
  id: string;
  title: string;
  category: 'Built-in (hosted)' | 'Embedded (your app runs it)' | 'Backend & APIs';
  audience: string;
  intro: string;
  code: Partial<Record<Lang, string>>;
}

export const RECIPES: Recipe[] = [
  {
    id: 'hosted-oidc',
    title: 'Sign in with the platform (OIDC authorization_code + PKCE)',
    category: 'Built-in (hosted)',
    audience: "Tenant's web app / SaaS / 3rd-party app",
    intro:
      "The recommended path: your app is just an OIDC client pointed at the tenant issuer. The hosted login provides password, MFA, social, passkey and SAML automatically — zero per-mechanism code. Add idp_hint to deep-link to a provider.",
    code: {
      TypeScript: [
        "import { UserManager } from 'oidc-client-ts';",
        '',
        'const mgr = new UserManager({',
        "  authority: 'https://ISSUER',            // your Aegis issuer (or https://ISSUER/{tenant})",
        "  client_id: 'acme-web',",
        "  redirect_uri: window.location.origin + '/callback',",
        "  response_type: 'code',                   // authorization_code + PKCE (automatic)",
        "  scope: 'openid profile',",
        '});',
        '',
        '// Start login (optionally straight to a provider):',
        "// mgr.signinRedirect({ extraQueryParams: { idp_hint: 'google' } });",
        'await mgr.signinRedirect();',
        '',
        '// On /callback:',
        'const user = await mgr.signinRedirectCallback();',
        'console.log(user.access_token, user.profile);',
      ].join('\n'),
      Python: [
        '# Flask + Authlib (confidential web app)',
        'from authlib.integrations.flask_client import OAuth',
        '',
        'oauth = OAuth(app)',
        'oauth.register(',
        '    name="aegis",',
        '    server_metadata_url="https://ISSUER/.well-known/openid-configuration",',
        '    client_id="acme-web", client_secret="SECRET",',
        '    client_kwargs={"scope": "openid profile", "code_challenge_method": "S256"},',
        ')',
        '',
        '@app.route("/login")',
        'def login():',
        '    return oauth.aegis.authorize_redirect(url_for("callback", _external=True))',
        '',
        '@app.route("/callback")',
        'def callback():',
        '    token = oauth.aegis.authorize_access_token()',
        '    return token["userinfo"]',
      ].join('\n'),
      Java: [
        '# application.yml  (spring-boot-starter-oauth2-client)',
        'spring:',
        '  security:',
        '    oauth2:',
        '      client:',
        '        provider:',
        '          aegis: { issuer-uri: https://ISSUER }        # or https://ISSUER/{tenant}',
        '        registration:',
        '          aegis:',
        '            client-id: acme-web',
        '            client-secret: SECRET',
        '            scope: openid,profile',
        '            authorization-grant-type: authorization_code',
        '            redirect-uri: "{baseUrl}/login/oauth2/code/aegis"',
        '',
        '// SecurityConfig.java — PKCE is automatic in Spring Security',
        '@Bean SecurityFilterChain chain(HttpSecurity http) throws Exception {',
        '  http.authorizeHttpRequests(a -> a.anyRequest().authenticated())',
        '      .oauth2Login(Customizer.withDefaults());',
        '  return http.build();',
        '}',
      ].join('\n'),
      Go: [
        '// github.com/coreos/go-oidc/v3 + golang.org/x/oauth2',
        'provider, _ := oidc.NewProvider(ctx, "https://ISSUER")',
        'cfg := oauth2.Config{',
        '    ClientID:    "acme-web",',
        '    RedirectURL: "https://app.acme.com/callback",',
        '    Endpoint:    provider.Endpoint(),',
        '    Scopes:      []string{oidc.ScopeOpenID, "profile"},',
        '}',
        '',
        'verifier := oauth2.GenerateVerifier()',
        '// Redirect the user (add oauth2.SetAuthURLParam("idp_hint","google") to deep-link):',
        'authURL := cfg.AuthCodeURL("state", oauth2.S256ChallengeOption(verifier))',
        '',
        '// On callback:',
        'tok, _ := cfg.Exchange(ctx, code, oauth2.VerifierOption(verifier))',
        'idToken := tok.Extra("id_token").(string)',
        'claims, _ := provider.Verifier(&oidc.Config{ClientID: "acme-web"}).Verify(ctx, idToken)',
      ].join('\n'),
    },
  },
  {
    id: 'm2m',
    title: 'Machine-to-machine token (client_credentials)',
    category: 'Backend & APIs',
    audience: "Tenant's SaaS backend / 3rd-party service",
    intro: 'A backend gets a token to call platform (or your own) APIs — no user involved. Create the service credential under Applications.',
    code: {
      TypeScript: [
        "const res = await fetch('https://ISSUER/oauth2/token', {",
        "  method: 'POST',",
        '  headers: {',
        "    'Content-Type': 'application/x-www-form-urlencoded',",
        "    Authorization: 'Basic ' + Buffer.from('acme-backend:SECRET').toString('base64'),",
        '  },',
        "  body: new URLSearchParams({ grant_type: 'client_credentials', scope: 'identity:users:read' }),",
        '});',
        'const { access_token } = await res.json();',
      ].join('\n'),
      Python: [
        'import requests',
        'access_token = requests.post(',
        '    "https://ISSUER/oauth2/token",',
        '    auth=("acme-backend", "SECRET"),',
        '    data={"grant_type": "client_credentials", "scope": "identity:users:read"},',
        ').json()["access_token"]',
      ].join('\n'),
      Java: [
        'var form = new LinkedMultiValueMap<String,String>();',
        'form.add("grant_type", "client_credentials");',
        'form.add("scope", "identity:users:read");',
        'Map<?,?> resp = RestClient.create().post()',
        '    .uri("https://ISSUER/oauth2/token")',
        '    .headers(h -> h.setBasicAuth("acme-backend", "SECRET"))',
        '    .contentType(MediaType.APPLICATION_FORM_URLENCODED)',
        '    .body(form).retrieve().body(Map.class);',
        'String accessToken = (String) resp.get("access_token");',
      ].join('\n'),
      Go: [
        '// golang.org/x/oauth2/clientcredentials',
        'cfg := clientcredentials.Config{',
        '    ClientID: "acme-backend", ClientSecret: "SECRET",',
        '    TokenURL: "https://ISSUER/oauth2/token",',
        '    Scopes:   []string{"identity:users:read"},',
        '}',
        'tok, _ := cfg.Token(ctx)   // tok.AccessToken',
      ].join('\n'),
    },
  },
  {
    id: 'verify',
    title: 'Verify Aegis tokens in your own API (resource server)',
    category: 'Backend & APIs',
    audience: "Tenant's SaaS API / 3rd-party API",
    intro: 'Protect your own API with Aegis-issued tokens: validate the signature against the JWKS and read the sub / tenant / scope claims.',
    code: {
      TypeScript: [
        "import { createRemoteJWKSet, jwtVerify } from 'jose';",
        "const JWKS = createRemoteJWKSet(new URL('https://ISSUER/oauth2/jwks'));",
        '',
        "const { payload } = await jwtVerify(bearerToken, JWKS, { issuer: 'https://ISSUER' });",
        'console.log(payload.sub, payload.tenant, payload.scope);',
      ].join('\n'),
      Python: [
        'import jwt',
        'from jwt import PyJWKClient',
        '',
        'jwks = PyJWKClient("https://ISSUER/oauth2/jwks")',
        'key = jwks.get_signing_key_from_jwt(token).key',
        'claims = jwt.decode(token, key, algorithms=["RS256"],',
        '                    issuer="https://ISSUER", options={"verify_aud": False})',
      ].join('\n'),
      Java: [
        '# application.yml (spring-boot-starter-oauth2-resource-server)',
        'spring:',
        '  security:',
        '    oauth2:',
        '      resourceserver:',
        '        jwt: { issuer-uri: https://ISSUER }',
        '',
        '// SecurityConfig.java',
        'http.oauth2ResourceServer(o -> o.jwt(Customizer.withDefaults()));',
        '// Scopes arrive as SCOPE_* authorities; read claims via @AuthenticationPrincipal Jwt.',
      ].join('\n'),
      Go: [
        'provider, _ := oidc.NewProvider(ctx, "https://ISSUER")',
        'verifier := provider.Verifier(&oidc.Config{SkipClientIDCheck: true})',
        'idt, err := verifier.Verify(ctx, bearerToken)',
        'var claims struct{ Sub, Tenant, Scope string }',
        '_ = idt.Claims(&claims)',
      ].join('\n'),
    },
  },
  {
    id: 'passkey-embedded',
    title: 'Embedded passkey login (your own web app)',
    category: 'Embedded (your app runs it)',
    audience: "Tenant's own web app",
    intro:
      'Run the WebAuthn ceremony in your app and swap the result for Aegis tokens. Configure your Relying Party first (Security → Passkeys: rpId + origins). The interaction-code endpoints are on the issuer with permissive CORS.',
    code: {
      TypeScript: [
        "const ISSUER = 'https://ISSUER', clientId = 'acme-web';",
        '',
        '// 1) options',
        "const opt = await (await fetch(ISSUER + '/api/v1/webauthn/login/options', {",
        "  method: 'POST', headers: { 'Content-Type': 'application/json' },",
        '  body: JSON.stringify({ clientId }),',
        '})).json();',
        '',
        '// 2) ceremony (b64url decode helpers omitted for brevity)',
        'const cred = await navigator.credentials.get({ publicKey: {',
        '  challenge: b64urlToBuf(opt.challenge), rpId: opt.rpId,',
        "  userVerification: 'preferred', allowCredentials: [],",
        '} }) as PublicKeyCredential;',
        'const r = cred.response as AuthenticatorAssertionResponse;',
        '',
        '// 3) finish -> interaction_code (PKCE)',
        'const codeVerifier = randomVerifier();',
        "const fin = await (await fetch(ISSUER + '/api/v1/webauthn/login/finish', {",
        "  method: 'POST', headers: { 'Content-Type': 'application/json' },",
        '  body: JSON.stringify({ clientId, codeChallenge: await s256(codeVerifier),',
        '    challengeId: opt.challengeId, credentialId: cred.id,',
        '    authenticatorData: bufToB64url(r.authenticatorData),',
        '    clientDataJSON: bufToB64url(r.clientDataJSON), signature: bufToB64url(r.signature),',
        '    userHandle: r.userHandle ? bufToB64url(r.userHandle) : null }),',
        '})).json();',
        '',
        '// 4) swap the interaction_code for tokens',
        "const tokens = await (await fetch(ISSUER + '/api/v1/oauth/interaction/token', {",
        "  method: 'POST', headers: { 'Content-Type': 'application/json' },",
        '  body: JSON.stringify({ clientId, interaction_code: fin.interaction_code, code_verifier: codeVerifier }),',
        '})).json();  // { access_token, id_token, ... }',
      ].join('\n'),
    },
  },
  {
    id: 'native-social',
    title: 'Native social + interaction-code exchange',
    category: 'Embedded (your app runs it)',
    audience: "Tenant's mobile app (native SDK)",
    intro:
      'Your app gets an id_token from the provider native SDK (Sign in with Apple / Google), exchanges it for an interaction_code, then swaps that for Aegis tokens. The two POSTs (below) are the exchange; the id_token comes from the native SDK.',
    code: {
      TypeScript: [
        "const ISSUER = 'https://ISSUER', clientId = 'acme-mobile';",
        'const codeVerifier = randomVerifier();',
        '',
        '// 1) provider id_token (from the native Google/Apple SDK) -> interaction_code',
        "const sx = await (await fetch(ISSUER + '/api/v1/social/native', {",
        "  method: 'POST', headers: { 'Content-Type': 'application/json' },",
        "  body: JSON.stringify({ clientId, provider: 'google', idToken: providerIdToken,",
        '    codeChallenge: await s256(codeVerifier) }),',
        '})).json();',
        '',
        '// 2) interaction_code -> Aegis tokens',
        "const tokens = await (await fetch(ISSUER + '/api/v1/oauth/interaction/token', {",
        "  method: 'POST', headers: { 'Content-Type': 'application/json' },",
        '  body: JSON.stringify({ clientId, interaction_code: sx.interaction_code, code_verifier: codeVerifier }),',
        '})).json();',
      ].join('\n'),
      Python: [
        'import requests',
        'ISSUER = "https://ISSUER"',
        '',
        'sx = requests.post(ISSUER + "/api/v1/social/native", json={',
        '    "clientId": "acme-mobile", "provider": "google",',
        '    "idToken": provider_id_token, "codeChallenge": s256(code_verifier),',
        '}).json()',
        '',
        'tokens = requests.post(ISSUER + "/api/v1/oauth/interaction/token", json={',
        '    "clientId": "acme-mobile", "interaction_code": sx["interaction_code"],',
        '    "code_verifier": code_verifier,',
        '}).json()',
      ].join('\n'),
      Java: [
        'var http = RestClient.create();',
        'Map<?,?> sx = http.post().uri("https://ISSUER/api/v1/social/native")',
        '    .contentType(MediaType.APPLICATION_JSON)',
        '    .body(Map.of("clientId","acme-mobile","provider","google",',
        '                 "idToken", providerIdToken, "codeChallenge", s256(codeVerifier)))',
        '    .retrieve().body(Map.class);',
        '',
        'Map<?,?> tokens = http.post().uri("https://ISSUER/api/v1/oauth/interaction/token")',
        '    .contentType(MediaType.APPLICATION_JSON)',
        '    .body(Map.of("clientId","acme-mobile",',
        '                 "interaction_code", sx.get("interaction_code"), "code_verifier", codeVerifier))',
        '    .retrieve().body(Map.class);',
      ].join('\n'),
      Go: [
        'post := func(path string, body any) map[string]any {',
        '    b, _ := json.Marshal(body)',
        '    resp, _ := http.Post("https://ISSUER"+path, "application/json", bytes.NewReader(b))',
        '    var out map[string]any; json.NewDecoder(resp.Body).Decode(&out); return out',
        '}',
        'sx := post("/api/v1/social/native", map[string]any{',
        '    "clientId": "acme-mobile", "provider": "google",',
        '    "idToken": providerIDToken, "codeChallenge": s256(codeVerifier)})',
        'tokens := post("/api/v1/oauth/interaction/token", map[string]any{',
        '    "clientId": "acme-mobile", "interaction_code": sx["interaction_code"], "code_verifier": codeVerifier})',
      ].join('\n'),
    },
  },
  {
    id: 'provision',
    title: 'Provision a user via the management API',
    category: 'Backend & APIs',
    audience: "Tenant's SaaS backend using the platform directory",
    intro: 'Use an M2M access token (above) to create/manage users through the gateway. Calls are tenant-scoped by the token.',
    code: {
      TypeScript: [
        "await fetch('https://GATEWAY/api/v1/users', {",
        "  method: 'POST',",
        "  headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + accessToken },",
        "  body: JSON.stringify({ username: 'jane', email: 'jane@acme.com', password: 'S3cret!x9' }),",
        '});',
      ].join('\n'),
      Python: [
        'requests.post("https://GATEWAY/api/v1/users",',
        '    headers={"Authorization": f"Bearer {access_token}"},',
        '    json={"username": "jane", "email": "jane@acme.com", "password": "S3cret!x9"})',
      ].join('\n'),
      Java: [
        'RestClient.create().post().uri("https://GATEWAY/api/v1/users")',
        '    .headers(h -> h.setBearerAuth(accessToken))',
        '    .contentType(MediaType.APPLICATION_JSON)',
        '    .body(Map.of("username","jane","email","jane@acme.com","password","S3cret!x9"))',
        '    .retrieve().toBodilessEntity();',
      ].join('\n'),
      Go: [
        'body, _ := json.Marshal(map[string]string{"username":"jane","email":"jane@acme.com","password":"S3cret!x9"})',
        'req, _ := http.NewRequest("POST", "https://GATEWAY/api/v1/users", bytes.NewReader(body))',
        'req.Header.Set("Authorization", "Bearer "+accessToken)',
        'req.Header.Set("Content-Type", "application/json")',
        'http.DefaultClient.Do(req)',
      ].join('\n'),
    },
  },
];
